# fly.toml app configuration file generated for shipping-discounts on 2025-03-12T23:27:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shipping-discounts'
primary_region = 'mia'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_discounts,write_products'
  SHOPIFY_API_KEY = '7e4a5e51dab6ed9b12f1bce219fce620'
  SHOPIFY_APP_URL = 'https://shipping-discounts.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
